# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# relative_permalinks: true
permalink:           pretty
# permalink config
# permalink:          /:year/:month/:day/:slug/

# Setup
title:               craigbeck.io
tagline:             ''
description:         ''
url:                 http://craigbeck.io
paginate:            5


# About/contact
author:
  name:              Craig beck
  url:               https://twitter.com/kreiggers
  email:             luckybonza@gmail.com
  github:            craigbeck

# Custom vars
version:             1.0.0

# require gems for build
plugins:
  - jekyll-paginate
  - classifier-reborn

# exclude files form build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - Makefile

collections:
  resources:
    output: true
